% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{float}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Thang\_Activity 33},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Thang\_Activity 33}
\author{}
\date{\vspace{-2.5em}2025-11-09}

\begin{document}
\maketitle

\subsection{1. Create a Table 1}\label{create-a-table-1}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Set global CRAN mirror}
\FunctionTok{options}\NormalTok{(}\AttributeTok{repos =} \FunctionTok{c}\NormalTok{(}\AttributeTok{CRAN =} \StringTok{"https://cran.rstudio.com/"}\NormalTok{))}

\DocumentationTok{\#\# Install the tableone package}
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"tableone"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Installing package into 'C:/Users/Thang/AppData/Local/R/win-library/4.3'
## (as 'lib' is unspecified)
\end{verbatim}

\begin{verbatim}
## package 'tableone' successfully unpacked and MD5 sums checked
## 
## The downloaded binary packages are in
##  C:\Users\Thang\AppData\Local\Temp\RtmpwvYfNf\downloaded_packages
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Load the required packages}

\FunctionTok{library}\NormalTok{(tableone)}
\FunctionTok{library}\NormalTok{(readxl)}
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(janitor)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'janitor'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     chisq.test, fisher.test
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(knitr)}

\CommentTok{\# 1. Import dataset {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}

\FunctionTok{setwd}\NormalTok{(}\StringTok{"C:/Users/Thang/OneDrive/Documents/ActivityData\_Assignment/Activity\_3"}\NormalTok{)}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"SuicideRisk\_Data.xlsx"}\NormalTok{)}

\CommentTok{\# 2. Inspect initial structure {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}

\FunctionTok{str}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## tibble [546 x 19] (S3: tbl_df/tbl/data.frame)
##  $ RECORD_ID      : num [1:546] 1 4 7 10 12 14 15 17 19 20 ...
##  $ AGE            : num [1:546] 24 25 21 23 21 22 28 36 24 27 ...
##  $ GENDER         : chr [1:546] "Female" "Female" "Female" "Female" ...
##  $ RACE           : chr [1:546] "White/Caucasian" "White/Caucasian" "White/Caucasian" "Asian" ...
##  $ ETHNICITY      : chr [1:546] "Not Hispanic/Latino" "Not Hispanic/Latino" "Not Hispanic/Latino" "Not Hispanic/Latino" ...
##  $ INCOME         : chr [1:546] ">$100,000" "$30,000 - $50,000" "$51,000 - $75,000" "$51,000 - $75,000" ...
##  $ ACES___1       : num [1:546] 0 0 0 0 0 0 0 0 0 0 ...
##  $ ACES___2       : num [1:546] 0 0 0 0 0 1 1 0 1 0 ...
##  $ ACES___3       : num [1:546] 0 0 0 0 0 1 1 0 1 0 ...
##  $ ACES___4       : num [1:546] 0 0 0 0 0 0 0 0 0 0 ...
##  $ ACES___5       : num [1:546] 0 0 0 0 0 0 0 0 0 0 ...
##  $ ACES___6       : num [1:546] 0 0 0 0 1 0 0 0 0 0 ...
##  $ ACES___7       : num [1:546] 0 0 1 0 0 0 0 0 0 0 ...
##  $ ACES___8       : num [1:546] 0 0 0 0 0 0 0 0 0 0 ...
##  $ ACES___9       : num [1:546] 1 0 0 1 0 1 0 1 0 0 ...
##  $ ACES___10      : num [1:546] 0 0 0 1 0 0 0 0 0 0 ...
##  $ CESDR_TOTAL_SUM: num [1:546] 8 15 2 20 9 2 18 0 2 9 ...
##  $ HX_SUICIDE     : num [1:546] 0 0 0 0 0 0 0 0 0 0 ...
##  $ SABCS_TOTAL_SUM: num [1:546] 0 0 0 0 1 0 5 1 0 2 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 3. Convert variables to correct types {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}

\NormalTok{data}\SpecialCharTok{$}\NormalTok{RECORD\_ID }\OtherTok{\textless{}{-}} \FunctionTok{as.integer}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{RECORD\_ID)}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{AGE }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{AGE)}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{CESDR\_TOTAL\_SUM }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{CESDR\_TOTAL\_SUM)}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{SABCS\_TOTAL\_SUM }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{SABCS\_TOTAL\_SUM)}

\CommentTok{\# Categorical variables}

\NormalTok{data}\SpecialCharTok{$}\NormalTok{GENDER }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{GENDER, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Female"}\NormalTok{, }\StringTok{"Male"}\NormalTok{))}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{RACE }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{RACE, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"White/Caucasian"}\NormalTok{, }\StringTok{"Asian"}\NormalTok{, }\StringTok{"Other"}\NormalTok{))}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{ETHNICITY }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{ETHNICITY,}
\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Hispanic/Latino"}\NormalTok{, }\StringTok{"Not Hispanic/Latino"}\NormalTok{))}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{INCOME }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{INCOME,}
\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"\textless{}$30,000"}\NormalTok{, }\StringTok{"$30,000 {-} $50,000"}\NormalTok{,}
\StringTok{"$51,000 {-} $75,000"}\NormalTok{, }\StringTok{"$76,000 {-} $100,000"}\NormalTok{,}
\StringTok{"\textgreater{}$100,000"}\NormalTok{))}

\CommentTok{\# Binary ACEs}

\NormalTok{aces\_vars }\OtherTok{\textless{}{-}} \FunctionTok{paste0}\NormalTok{(}\StringTok{"ACES\_\_\_"}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{)}
\NormalTok{data[aces\_vars] }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(data[aces\_vars], factor,}
\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{), }\AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"No"}\NormalTok{, }\StringTok{"Yes"}\NormalTok{))}

\CommentTok{\# Suicide history variable (must exist before CreateTableOne)}

\NormalTok{data}\SpecialCharTok{$}\NormalTok{HX\_SUICIDE }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{HX\_SUICIDE,}
\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{),}
\AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"History of Suicide"}\NormalTok{, }\StringTok{"No History of Suicide"}\NormalTok{))}

\CommentTok{\# Confirm it exists}

\FunctionTok{table}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{HX\_SUICIDE)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    History of Suicide No History of Suicide 
##                    49                   497
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 4. Define variables for Table 1 {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}

\NormalTok{vars }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"AGE"}\NormalTok{, }\StringTok{"GENDER"}\NormalTok{, }\StringTok{"RACE"}\NormalTok{, }\StringTok{"ETHNICITY"}\NormalTok{, }\StringTok{"INCOME"}\NormalTok{,}
\NormalTok{aces\_vars, }\StringTok{"CESDR\_TOTAL\_SUM"}\NormalTok{, }\StringTok{"SABCS\_TOTAL\_SUM"}\NormalTok{)}

\NormalTok{catVars }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"GENDER"}\NormalTok{, }\StringTok{"RACE"}\NormalTok{, }\StringTok{"ETHNICITY"}\NormalTok{, }\StringTok{"INCOME"}\NormalTok{, aces\_vars)}

\CommentTok{\# 5. Create Table 1 {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}

\NormalTok{table1 }\OtherTok{\textless{}{-}} \FunctionTok{CreateTableOne}\NormalTok{(}
\AttributeTok{vars =}\NormalTok{ vars,}
\AttributeTok{strata =} \StringTok{"HX\_SUICIDE"}\NormalTok{,}
\AttributeTok{data =}\NormalTok{ data,}
\AttributeTok{factorVars =}\NormalTok{ catVars,}
\AttributeTok{addOverall =} \ConstantTok{TRUE}\NormalTok{,}
\AttributeTok{test =} \ConstantTok{TRUE}
\NormalTok{)}

\CommentTok{\# 6. Convert to data frame {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}

\NormalTok{table1\_df }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{print}\NormalTok{(table1, }\AttributeTok{test =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{smd =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                                      Stratified by HX_SUICIDE
##                                       Overall       History of Suicide
##   n                                     546            49             
##   AGE (mean (SD))                     24.85 (6.50)  25.69 (7.11)      
##   GENDER = Male (%)                      47 ( 8.6)      5 (10.2)      
##   RACE (%)                                                            
##      White/Caucasian                    392 (71.8)     38 (77.6)      
##      Asian                               63 (11.5)      5 (10.2)      
##      Other                               91 (16.7)      6 (12.2)      
##   ETHNICITY = Not Hispanic/Latino (%)   478 (87.5)     38 (77.6)      
##   INCOME (%)                                                          
##      $30,000 - $50,000                  101 (23.1)     11 (30.6)      
##      $51,000 - $75,000                  108 (24.7)      7 (19.4)      
##      $76,000 - $100,000                 106 (24.2)      8 (22.2)      
##      >$100,000                          123 (28.1)     10 (27.8)      
##   ACES___1 = Yes (%)                     66 (12.1)     13 (26.5)      
##   ACES___2 = Yes (%)                     95 (17.4)     26 (53.1)      
##   ACES___3 = Yes (%)                    158 (28.9)     31 (63.3)      
##   ACES___4 = Yes (%)                     18 ( 3.3)      4 ( 8.2)      
##   ACES___5 = Yes (%)                     64 (11.7)     10 (20.4)      
##   ACES___6 = Yes (%)                     86 (15.8)     14 (28.6)      
##   ACES___7 = Yes (%)                     76 (13.9)     11 (22.4)      
##   ACES___8 = Yes (%)                    119 (21.8)     25 (51.0)      
##   ACES___9 = Yes (%)                    156 (28.6)     22 (44.9)      
##   ACES___10 = Yes (%)                    27 ( 4.9)      7 (14.3)      
##   CESDR_TOTAL_SUM (mean (SD))         15.77 (13.70) 27.63 (15.52)     
##   SABCS_TOTAL_SUM (mean (SD))          3.31 (4.86)  10.63 (6.83)      
##                                      Stratified by HX_SUICIDE
##                                       No History of Suicide p      test SMD   
##   n                                     497                                   
##   AGE (mean (SD))                     24.77 (6.44)           0.342       0.137
##   GENDER = Male (%)                      42 ( 8.5)           0.880       0.060
##   RACE (%)                                                   0.618       0.153
##      White/Caucasian                    354 (71.2)                            
##      Asian                               58 (11.7)                            
##      Other                               85 (17.1)                            
##   ETHNICITY = Not Hispanic/Latino (%)   440 (88.5)           0.046       0.296
##   INCOME (%)                                                 0.693       0.205
##      $30,000 - $50,000                   90 (22.4)                            
##      $51,000 - $75,000                  101 (25.1)                            
##      $76,000 - $100,000                  98 (24.4)                            
##      >$100,000                          113 (28.1)                            
##   ACES___1 = Yes (%)                     53 (10.7)           0.003       0.417
##   ACES___2 = Yes (%)                     69 (13.9)          <0.001       0.913
##   ACES___3 = Yes (%)                    127 (25.6)          <0.001       0.820
##   ACES___4 = Yes (%)                     14 ( 2.8)           0.114       0.236
##   ACES___5 = Yes (%)                     54 (10.9)           0.080       0.265
##   ACES___6 = Yes (%)                     72 (14.5)           0.017       0.348
##   ACES___7 = Yes (%)                     65 (13.1)           0.111       0.247
##   ACES___8 = Yes (%)                     94 (18.9)          <0.001       0.715
##   ACES___9 = Yes (%)                    134 (27.0)           0.013       0.381
##   ACES___10 = Yes (%)                    20 ( 4.0)           0.005       0.362
##   CESDR_TOTAL_SUM (mean (SD))         14.60 (12.95)         <0.001       0.912
##   SABCS_TOTAL_SUM (mean (SD))          2.58 (3.95)          <0.001       1.442
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 7. Rename and reorder columns {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}

\FunctionTok{names}\NormalTok{(table1\_df) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Characteristic"}\NormalTok{,}
\StringTok{"Total (n = 546)"}\NormalTok{,}
\StringTok{"History of Suicide"}\NormalTok{,}
\StringTok{"No History of Suicide"}\NormalTok{,}
\StringTok{"P{-}value"}\NormalTok{,}
\StringTok{"Effect Size"}\NormalTok{)}

\NormalTok{table1\_df }\OtherTok{\textless{}{-}}\NormalTok{ table1\_df[, }\FunctionTok{c}\NormalTok{(}\StringTok{"Characteristic"}\NormalTok{,}
\StringTok{"Total (n = 546)"}\NormalTok{,}
\StringTok{"History of Suicide"}\NormalTok{,}
\StringTok{"No History of Suicide"}\NormalTok{,}
\StringTok{"Effect Size"}\NormalTok{,}
\StringTok{"P{-}value"}\NormalTok{)]}

\CommentTok{\# 8. Display nicely {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\FunctionTok{library}\NormalTok{(kableExtra)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'kableExtra'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:dplyr':
## 
##     group_rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{(table1\_df,}
      \AttributeTok{caption =} \StringTok{"Table 1. Demographic and Mental Health Characteristics (n = 546)"}\NormalTok{,}
      \AttributeTok{booktabs =} \ConstantTok{TRUE}\NormalTok{,}
      \AttributeTok{align =} \StringTok{"lccccc"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{footnote}\NormalTok{(}
    \AttributeTok{general =} \StringTok{"Continuous variables are shown as mean ± SD; categorical variables }
\StringTok{    as n (\%). P{-}values are derived from t{-}tests or Chi{-}square tests as }
\StringTok{    appropriate. Effect Size = Standardized Mean Difference (SMD). }
\StringTok{    ACEs = Adverse Childhood Experiences; CESDR = Center for Epidemiologic }
\StringTok{    Studies Depression Scale; SABCS = Suicidal Affect–Behavior–Cognition Scale."}\NormalTok{,}
    \AttributeTok{general\_title =} \StringTok{"Note:"}\NormalTok{,}
    \AttributeTok{threeparttable =} \ConstantTok{TRUE}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Note:} 
\item makecell[l]{Continuous variables are shown as mean ± SD; categorical variables \    as n (\%). P-values are derived from t-tests or Chi-square tests as \    appropriate. Effect Size = Standardized Mean Difference (SMD). \    ACEs = Adverse Childhood Experiences; CESDR = Center for Epidemiologic \    Studies Depression Scale; SABCS = Suicidal Affect–Behavior–Cognition Scale.}
\end{TableNotes}
\begin{longtable}[t]{llccccc}
\caption{\label{tab:unnamed-chunk-1}Table 1. Demographic and Mental Health Characteristics (n = 546)}\\
\toprule
 & Characteristic & Total (n = 546) & History of Suicide & No History of Suicide & Effect Size & P-value\\
\midrule
n & 546 & 49 & 497 &  &  & \\
AGE (mean (SD)) & 24.85 (6.50) & 25.69 (7.11) & 24.77 (6.44) & 0.342 & 0.137 & \\
GENDER = Male (\%) & 47 ( 8.6) & 5 (10.2) & 42 ( 8.5) & 0.880 & 0.060 & \\
RACE (\%) &  &  &  & 0.618 & 0.153 & \\
White/Caucasian & 392 (71.8) & 38 (77.6) & 354 (71.2) &  &  & \\
\addlinespace
Asian & 63 (11.5) & 5 (10.2) & 58 (11.7) &  &  & \\
Other & 91 (16.7) & 6 (12.2) & 85 (17.1) &  &  & \\
ETHNICITY = Not Hispanic/Latino (\%) & 478 (87.5) & 38 (77.6) & 440 (88.5) & 0.046 & 0.296 & \\
INCOME (\%) &  &  &  & 0.693 & 0.205 & \\
\$30,000 - \$50,000 & 101 (23.1) & 11 (30.6) & 90 (22.4) &  &  & \\
\addlinespace
\$51,000 - \$75,000 & 108 (24.7) & 7 (19.4) & 101 (25.1) &  &  & \\
\$76,000 - \$100,000 & 106 (24.2) & 8 (22.2) & 98 (24.4) &  &  & \\
>\$100,000 & 123 (28.1) & 10 (27.8) & 113 (28.1) &  &  & \\
ACES\_\_\_1 = Yes (\%) & 66 (12.1) & 13 (26.5) & 53 (10.7) & 0.003 & 0.417 & \\
ACES\_\_\_2 = Yes (\%) & 95 (17.4) & 26 (53.1) & 69 (13.9) & <0.001 & 0.913 & \\
\addlinespace
ACES\_\_\_3 = Yes (\%) & 158 (28.9) & 31 (63.3) & 127 (25.6) & <0.001 & 0.820 & \\
ACES\_\_\_4 = Yes (\%) & 18 ( 3.3) & 4 ( 8.2) & 14 ( 2.8) & 0.114 & 0.236 & \\
ACES\_\_\_5 = Yes (\%) & 64 (11.7) & 10 (20.4) & 54 (10.9) & 0.080 & 0.265 & \\
ACES\_\_\_6 = Yes (\%) & 86 (15.8) & 14 (28.6) & 72 (14.5) & 0.017 & 0.348 & \\
ACES\_\_\_7 = Yes (\%) & 76 (13.9) & 11 (22.4) & 65 (13.1) & 0.111 & 0.247 & \\
\addlinespace
ACES\_\_\_8 = Yes (\%) & 119 (21.8) & 25 (51.0) & 94 (18.9) & <0.001 & 0.715 & \\
ACES\_\_\_9 = Yes (\%) & 156 (28.6) & 22 (44.9) & 134 (27.0) & 0.013 & 0.381 & \\
ACES\_\_\_10 = Yes (\%) & 27 ( 4.9) & 7 (14.3) & 20 ( 4.0) & 0.005 & 0.362 & \\
CESDR\_TOTAL\_SUM (mean (SD)) & 15.77 (13.70) & 27.63 (15.52) & 14.60 (12.95) & <0.001 & 0.912 & \\
SABCS\_TOTAL\_SUM (mean (SD)) & 3.31 (4.86) & 10.63 (6.83) & 2.58 (3.95) & <0.001 & 1.442 & \\
\bottomrule
\insertTableNotes
\end{longtable}
\end{ThreePartTable}

\section{Significant characteristic (p \textless{}
0.05)}\label{significant-characteristic-p-0.05}

Participants with a history of suicide were significantly more likely to
identify as Hispanic or Latino compared to those without a suicide
history. This suggests that cultural or social factors associated with
ethnicity may be related to suicide risk in this sample, although the
result shows association---not causation.

\section{Non-significant characteristic (p ≥
0.05)}\label{non-significant-characteristic-p-0.05}

The average age did not differ significantly between participants with
and without a history of suicide. This means that age alone was not
associated with suicide history in this study, and both groups had
similar age distributions.

\subsection{2. This problem will focus on comparing suicidal risk
(Suicidal Affect-Behavior-Cognition Scale {[}SABCS{]}) across race
groups (White/Caucasian vs Asian vs
Other).}\label{this-problem-will-focus-on-comparing-suicidal-risk-suicidal-affect-behavior-cognition-scale-sabcs-across-race-groups-whitecaucasian-vs-asian-vs-other.}

\section{A. Group comparison}\label{a.-group-comparison}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load necessary packages}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"psych"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Installing package into 'C:/Users/Thang/AppData/Local/R/win-library/4.3'
## (as 'lib' is unspecified)
\end{verbatim}

\begin{verbatim}
## 
##   There is a binary version available but the source version is later:
##       binary source needs_compilation
## psych  2.5.3  2.5.6             FALSE
\end{verbatim}

\begin{verbatim}
## installing the source package 'psych'
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(psych)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'psych'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:ggplot2':
## 
##     %+%, alpha
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 1. Descriptive statistics by race}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(RACE) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{n =} \FunctionTok{n}\NormalTok{(),}
    \AttributeTok{mean\_SABCS =} \FunctionTok{mean}\NormalTok{(SABCS\_TOTAL\_SUM, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{sd\_SABCS =} \FunctionTok{sd}\NormalTok{(SABCS\_TOTAL\_SUM, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{median\_SABCS =} \FunctionTok{median}\NormalTok{(SABCS\_TOTAL\_SUM, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{IQR\_SABCS =} \FunctionTok{IQR}\NormalTok{(SABCS\_TOTAL\_SUM, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 6
##   RACE                n mean_SABCS sd_SABCS median_SABCS IQR_SABCS
##   <fct>           <int>      <dbl>    <dbl>        <dbl>     <dbl>
## 1 White/Caucasian   392       3.16     4.69            1         4
## 2 Asian              63       3.65     5.38            1         5
## 3 Other              91       3.71     5.23            2         5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 2. Visualization: Boxplot of SABCS by Race}
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ RACE, }\AttributeTok{y =}\NormalTok{ SABCS\_TOTAL\_SUM, }\AttributeTok{fill =}\NormalTok{ RACE)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.2}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.4}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Distribution of Suicidal Risk (SABCS) Across Race Groups"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Race Group"}\NormalTok{, }\AttributeTok{y =} \StringTok{"SABCS Total Score"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"none"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Activity-3_trial1_files/figure-latex/unnamed-chunk-2-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 3. Run one{-}way ANOVA}
\NormalTok{anova\_model }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(SABCS\_TOTAL\_SUM }\SpecialCharTok{\textasciitilde{}}\NormalTok{ RACE, }\AttributeTok{data =}\NormalTok{ data)}
\FunctionTok{summary}\NormalTok{(anova\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Df Sum Sq Mean Sq F value Pr(>F)
## RACE          2     32   15.76   0.667  0.514
## Residuals   543  12838   23.64
\end{verbatim}

The distribution of suicidal risk scores (SABCS) showed similar patterns
across the three racial groups. White/Caucasian participants had a mean
score of 3.16 (SD = 4.69) with a median of 1 and an IQR of 4, indicating
a right-skewed distribution with many low scores and a long tail of
higher scores. Asian participants exhibited a slightly higher mean
(3.65, SD = 5.38) and a median of 1, with an IQR of 5, suggesting
greater spread and more variability in suicidal risk. Participants in
the ``Other'' race category had the highest median (2) and an IQR of 5,
with a mean of 3.71 (SD = 5.23), also reflecting a skewed distribution
with several high-risk values.

\section{B \& C. Checking assumptions AND Post-hoc
analysis}\label{b-c.-checking-assumptions-and-post-hoc-analysis}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check homogeneity of variances (Levene’s test)}
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"car"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Installing package into 'C:/Users/Thang/AppData/Local/R/win-library/4.3'
## (as 'lib' is unspecified)
\end{verbatim}

\begin{verbatim}
## package 'car' successfully unpacked and MD5 sums checked
## 
## The downloaded binary packages are in
##  C:\Users\Thang\AppData\Local\Temp\RtmpwvYfNf\downloaded_packages
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(car)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: carData
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'car'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:psych':
## 
##     logit
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:dplyr':
## 
##     recode
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{leveneTest}\NormalTok{(SABCS\_TOTAL\_SUM }\SpecialCharTok{\textasciitilde{}}\NormalTok{ RACE, }\AttributeTok{data =}\NormalTok{ data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Levene's Test for Homogeneity of Variance (center = median)
##        Df F value Pr(>F)
## group   2  0.6178 0.5395
##       543
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check normality of residuals}
\FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{residuals}\NormalTok{(anova\_model))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(anova_model)
## W = 0.72477, p-value < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualization of residuals}
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(anova\_model, }\AttributeTok{which =} \DecValTok{1}\NormalTok{)  }\CommentTok{\# Residuals vs Fitted}
\FunctionTok{plot}\NormalTok{(anova\_model, }\AttributeTok{which =} \DecValTok{2}\NormalTok{)  }\CommentTok{\# Q{-}Q plot}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Activity-3_trial1_files/figure-latex/unnamed-chunk-3-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Levene's test indicated that the assumption of homogeneity of variances
was met (p = 0.54). However, the Shapiro--Wilk test showed that the
ANOVA residuals were significantly non-normal (p \textless{} 0.001),
suggesting substantial deviation from normality. Given the large sample
size, ANOVA results remain relatively robust, but a non-parametric
alternative (e.g., Kruskal--Wallis test) may provide a more appropriate
assessment.

The one-way ANOVA showed no statistically significant differences in
mean suicidal risk (SABCS) across race groups (p \textgreater{} 0.05).
Therefore, post-hoc pairwise comparisons were not conducted.

\#D AND E. Linear Regression AND CompaCompare/Contrast your Results

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Make sure reference category is White/Caucasian}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{RACE }\OtherTok{\textless{}{-}} \FunctionTok{relevel}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{RACE, }\AttributeTok{ref =} \StringTok{"White/Caucasian"}\NormalTok{)}

\CommentTok{\# Fit the linear regression model}
\NormalTok{lm\_model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(SABCS\_TOTAL\_SUM }\SpecialCharTok{\textasciitilde{}}\NormalTok{ RACE, }\AttributeTok{data =}\NormalTok{ data)}

\CommentTok{\# Show summary}
\FunctionTok{summary}\NormalTok{(lm\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = SABCS_TOTAL_SUM ~ RACE, data = data)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.714 -3.156 -2.156  1.175 28.844 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   3.1556     0.2456  12.849   <2e-16 ***
## RACEAsian     0.4952     0.6600   0.750    0.453    
## RACEOther     0.5587     0.5658   0.987    0.324    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.862 on 543 degrees of freedom
## Multiple R-squared:  0.002449,   Adjusted R-squared:  -0.001225 
## F-statistic: 0.6667 on 2 and 543 DF,  p-value: 0.5138
\end{verbatim}

\section{Linear Regression Interpretation (plain language, alpha =
0.05)}\label{linear-regression-interpretation-plain-language-alpha-0.05}

The linear regression model showed no statistically significant
differences in suicidal risk (SABCS scores) between race groups (overall
p = 0.51). Specifically, Asian participants (p = 0.45) and those in the
``Other'' race category (p = 0.32) did not differ significantly in
suicidal risk compared with White/Caucasian participants, the reference
group.

\section{Compare and Contrast with ANOVA
Results}\label{compare-and-contrast-with-anova-results}

Both the ANOVA and regression examined differences in suicidal risk by
race and reached the same conclusion: there were no significant
differences in mean SABCS scores across racial groups. The regression
quantified these differences relative to the White/Caucasian group,
while the ANOVA tested for any overall group difference. Together, both
analyses indicate that race was not a significant predictor of suicidal
risk in this sample.

\subsection{3. This problem will focus on comparing suicidal risk
(Suicidal Affect-Behavior-Cognition Scale {[}SABCS{]}) across the five
income
groups}\label{this-problem-will-focus-on-comparing-suicidal-risk-suicidal-affect-behavior-cognition-scale-sabcs-across-the-five-income-groups}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# A. Group comparison for INCOME}

\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(ggplot2)}

\CommentTok{\# 1. Summary stats by INCOME}
\NormalTok{income\_summary }\OtherTok{\textless{}{-}}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(INCOME) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{n =} \FunctionTok{n}\NormalTok{(),}
    \AttributeTok{mean\_SABCS =} \FunctionTok{mean}\NormalTok{(SABCS\_TOTAL\_SUM, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{sd\_SABCS =} \FunctionTok{sd}\NormalTok{(SABCS\_TOTAL\_SUM, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{median\_SABCS =} \FunctionTok{median}\NormalTok{(SABCS\_TOTAL\_SUM, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{IQR\_SABCS =} \FunctionTok{IQR}\NormalTok{(SABCS\_TOTAL\_SUM, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  )}

\NormalTok{income\_summary}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 5 x 6
##   INCOME                 n mean_SABCS sd_SABCS median_SABCS IQR_SABCS
##   <fct>              <int>      <dbl>    <dbl>        <dbl>     <dbl>
## 1 $30,000 - $50,000    101       3.32     4.92            1       4  
## 2 $51,000 - $75,000    108       2.36     4.16            1       3  
## 3 $76,000 - $100,000   106       2.95     4.25            1       4  
## 4 >$100,000            123       3.34     5.29            1       4.5
## 5 <NA>                 108       4.55     5.30            3       7
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 2. Visualization}
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ INCOME, }\AttributeTok{y =}\NormalTok{ SABCS\_TOTAL\_SUM, }\AttributeTok{fill =}\NormalTok{ INCOME)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.15}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.4}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Distribution of Suicidal Risk (SABCS) Across Income Groups"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Income Group"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"SABCS Total Score"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"none"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Activity-3_trial1_files/figure-latex/unnamed-chunk-5-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 3. One{-}way ANOVA}
\NormalTok{anova\_income }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(SABCS\_TOTAL\_SUM }\SpecialCharTok{\textasciitilde{}}\NormalTok{ INCOME, }\AttributeTok{data =}\NormalTok{ data)}
\FunctionTok{summary}\NormalTok{(anova\_income)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Df Sum Sq Mean Sq F value Pr(>F)
## INCOME        3     69   22.93   1.039  0.375
## Residuals   434   9583   22.08               
## 108 observations deleted due to missingness
\end{verbatim}

\section{A. Group comparison}\label{a.-group-comparison-1}

Across the five income groups, suicidal-risk scores (SABCS) showed
similarly right-skewed distributions, with most participants reporting
low scores and a smaller subset showing higher levels of risk. Median
scores and variability were generally comparable across income levels,
although slightly greater spread was observed in the lower-income and
middle-income groups. Overall, no clear visual differences in central
tendency or distribution shape were evident among the five groups.

\#B. CHECKING ASSUMPTION

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Levene test}
\FunctionTok{library}\NormalTok{(car)}
\FunctionTok{leveneTest}\NormalTok{(SABCS\_TOTAL\_SUM }\SpecialCharTok{\textasciitilde{}}\NormalTok{ INCOME, }\AttributeTok{data =}\NormalTok{ data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Levene's Test for Homogeneity of Variance (center = median)
##        Df F value Pr(>F)
## group   3  0.6701 0.5708
##       434
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Shapiro–Wilk for residuals}
\FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{residuals}\NormalTok{(anova\_income))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(anova_income)
## W = 0.69541, p-value < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Residual plots}
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(anova\_income, }\AttributeTok{which =} \DecValTok{1}\NormalTok{)  }\CommentTok{\# Residuals vs Fitted}
\FunctionTok{plot}\NormalTok{(anova\_income, }\AttributeTok{which =} \DecValTok{2}\NormalTok{)  }\CommentTok{\# QQ plot}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Activity-3_trial1_files/figure-latex/unnamed-chunk-6-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Levene's test indicated that the assumption of homogeneity of variances
across the five income groups was satisfied (F(3,434) = 0.67, p = 0.57).
However, the Shapiro--Wilk test showed that the ANOVA residuals were
strongly non-normal (W = 0.695, p \textless{} 0.001), reflecting
substantial skewness in the suicidal-risk data. Although ANOVA is
generally robust to non-normality with large samples, the severity of
this violation suggests that a non-parametric alternative may be more
appropriate as a confirmatory analysis.

\section{POST-HOC TESTTEST}\label{post-hoc-testtest}

Because the one-way ANOVA did not find a statistically significant
difference in suicidal-risk scores across the five income groups (p =
0.375), post-hoc pairwise comparisons were not conducted. Post-hoc tests
are only meaningful when the overall ANOVA indicates that at least one
group mean differs significantly from the others. Since this was not the
case, additional comparisons would not provide useful or interpretable
information.

\subsection{4. This problem will focus on comparing suicidal risk
(Suicidal Affect-Behavior-Cognition Scale {[}SABCS{]}) across the two
gender
groups.}\label{this-problem-will-focus-on-comparing-suicidal-risk-suicidal-affect-behavior-cognition-scale-sabcs-across-the-two-gender-groups.}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check group sizes and means}
\FunctionTok{table}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{GENDER)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Female   Male 
##    499     47
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tapply}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{SABCS\_TOTAL\_SUM, data}\SpecialCharTok{$}\NormalTok{GENDER, mean, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Female     Male 
## 3.334669 3.000000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tapply}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{SABCS\_TOTAL\_SUM, data}\SpecialCharTok{$}\NormalTok{GENDER, sd, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Female     Male 
## 4.764559 5.823491
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Perform independent samples t{-}test}
\NormalTok{t\_test\_gender }\OtherTok{\textless{}{-}} \FunctionTok{t.test}\NormalTok{(SABCS\_TOTAL\_SUM }\SpecialCharTok{\textasciitilde{}}\NormalTok{ GENDER, }\AttributeTok{data =}\NormalTok{ data, }\AttributeTok{var.equal =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{t\_test\_gender}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Two Sample t-test
## 
## data:  SABCS_TOTAL_SUM by GENDER
## t = 0.45104, df = 544, p-value = 0.6521
## alternative hypothesis: true difference in means between group Female and group Male is not equal to 0
## 95 percent confidence interval:
##  -1.122868  1.792207
## sample estimates:
## mean in group Female   mean in group Male 
##             3.334669             3.000000
\end{verbatim}

The two-sample t-test showed no significant difference in suicidal risk
(SABCS scores) between female and male participants (t(544) = 0.45, p =
0.65). On average, women and men reported similar levels of suicidal
thoughts, behaviors, and feelings in this sample.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}\SpecialCharTok{$}\NormalTok{GENDER }\OtherTok{\textless{}{-}} \FunctionTok{relevel}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{GENDER, }\AttributeTok{ref =} \StringTok{"Female"}\NormalTok{)}
\NormalTok{lm\_gender }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(SABCS\_TOTAL\_SUM }\SpecialCharTok{\textasciitilde{}}\NormalTok{ GENDER, }\AttributeTok{data =}\NormalTok{ data)}
\FunctionTok{summary}\NormalTok{(lm\_gender)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = SABCS_TOTAL_SUM ~ GENDER, data = data)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.335 -3.335 -2.335  1.415 29.000 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   3.3347     0.2177  15.318   <2e-16 ***
## GENDERMale   -0.3347     0.7420  -0.451    0.652    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.863 on 544 degrees of freedom
## Multiple R-squared:  0.0003738,  Adjusted R-squared:  -0.001464 
## F-statistic: 0.2034 on 1 and 544 DF,  p-value: 0.6521
\end{verbatim}

\section{Group comnparison}\label{group-comnparison}

The regression analysis confirmed that gender was not a significant
predictor of suicidal risk (p = 0.65). Male participants scored, on
average, 0.33 points lower on the SABCS scale than female participants,
but this small difference was not statistically meaningful.

\#Compare and contrast Both the t-test and the regression model produced
identical results---gender was not associated with differences in
suicidal-risk scores. The t-test directly compared mean SABCS scores
between females and males, while the regression estimated the mean
difference using females as the reference category. Together, the
findings indicate that gender did not play a significant role in
suicidal risk within this sample.

\subsection{5. This problem will focus on quantifying the association
between suicidal risk (Suicidal Affect-Behavior-Cognition Scale
{[}SABCS{]}) and depression (CESD-R), including the form, direction, and
strength of their
relationship.}\label{this-problem-will-focus-on-quantifying-the-association-between-suicidal-risk-suicidal-affect-behavior-cognition-scale-sabcs-and-depression-cesd-r-including-the-form-direction-and-strength-of-their-relationship.}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}

\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ CESDR\_TOTAL\_SUM, }\AttributeTok{y =}\NormalTok{ SABCS\_TOTAL\_SUM)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{color =} \StringTok{"\#2E86AB"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{color =} \StringTok{"\#E74C3C"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Relationship Between Depression (CESD{-}R) and Suicidal Risk (SABCS)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Depression (CESD{-}R Total Score)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Suicidal Risk (SABCS Total Score)"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Activity-3_trial1_files/figure-latex/unnamed-chunk-9-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cor\_test }\OtherTok{\textless{}{-}} \FunctionTok{cor.test}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{SABCS\_TOTAL\_SUM, }
\NormalTok{                     data}\SpecialCharTok{$}\NormalTok{CESDR\_TOTAL\_SUM, }\AttributeTok{method =} \StringTok{"pearson"}\NormalTok{)}
\NormalTok{cor\_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  data$SABCS_TOTAL_SUM and data$CESDR_TOTAL_SUM
## t = 17.013, df = 544, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.5316841 0.6414951
## sample estimates:
##       cor 
## 0.5893046
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check linearity visually}
\FunctionTok{plot}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{CESDR\_TOTAL\_SUM, data}\SpecialCharTok{$}\NormalTok{SABCS\_TOTAL\_SUM,}
     \AttributeTok{main =} \StringTok{"Scatterplot to Assess Linearity"}\NormalTok{,}
     \AttributeTok{xlab =} \StringTok{"Depression (CESD{-}R)"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Suicidal Risk (SABCS)"}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\FunctionTok{lm}\NormalTok{(SABCS\_TOTAL\_SUM }\SpecialCharTok{\textasciitilde{}}\NormalTok{ CESDR\_TOTAL\_SUM, }\AttributeTok{data =}\NormalTok{ data), }\AttributeTok{col =} \StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Activity-3_trial1_files/figure-latex/unnamed-chunk-9-2.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check normality of both variables}
\FunctionTok{shapiro.test}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{CESDR\_TOTAL\_SUM)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  data$CESDR_TOTAL_SUM
## W = 0.90079, p-value < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{SABCS\_TOTAL\_SUM)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  data$SABCS_TOTAL_SUM
## W = 0.7098, p-value < 2.2e-16
\end{verbatim}

\section{Visualization:}\label{visualization}

The scatterplot demonstrates a clear positive linear relationship
between depression (CESD-R) and suicidal risk (SABCS). As depression
scores increase, suicidal risk scores also tend to rise. The regression
line indicates that this relationship is approximately linear.

\section{Estimation:}\label{estimation}

The Pearson correlation coefficient between depression and suicidal risk
was r = 0.589 (95\% CI {[}0.53, 0.64{]}), indicating a moderate to
strong positive association. This means that participants with higher
depression levels generally reported higher suicidal risk.

\section{Test of assumptions:}\label{test-of-assumptions}

Visual inspection of the scatterplot suggests that the relationship is
linear. However, Shapiro--Wilk tests showed both variables deviate from
normality (p \textless{} 0.001). Given the large sample size (n = 546),
the Pearson correlation remains valid because the method is robust to
mild non-normality when sample sizes are large.

\section{Test of correlation (α =
0.05):}\label{test-of-correlation-ux3b1-0.05}

The correlation was statistically significant (t(544) = 17.01, p
\textless{} 0.001). In plain language:

There is a significant positive relationship between depression and
suicidal risk. Participants with higher depression scores also tend to
experience greater suicidal thoughts, feelings, and behaviors. The
strength of the association suggests that depression is an important
factor closely linked to suicidal risk in this sample.

\section{Visualization for linear
regression}\label{visualization-for-linear-regression}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# {-}{-}{-}{-} Linear Regression: Depression predicting Suicidal Risk {-}{-}{-}{-}}

\CommentTok{\# Fit simple linear regression model}
\NormalTok{lm\_line }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(SABCS\_TOTAL\_SUM }\SpecialCharTok{\textasciitilde{}}\NormalTok{ CESDR\_TOTAL\_SUM, }\AttributeTok{data =}\NormalTok{ data)}

\CommentTok{\# Display summary of regression results}
\FunctionTok{summary}\NormalTok{(lm\_line)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = SABCS_TOTAL_SUM ~ CESDR_TOTAL_SUM, data = data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.2968  -2.1009  -0.4739   0.9891  21.3302 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(>|t|)    
## (Intercept)      0.01088    0.25650   0.042    0.966    
## CESDR_TOTAL_SUM  0.20900    0.01228  17.013   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.93 on 544 degrees of freedom
## Multiple R-squared:  0.3473, Adjusted R-squared:  0.3461 
## F-statistic: 289.4 on 1 and 544 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#  Visualization: scatterplot + regression line}
\FunctionTok{library}\NormalTok{(ggplot2)}

\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ CESDR\_TOTAL\_SUM, }\AttributeTok{y =}\NormalTok{ SABCS\_TOTAL\_SUM)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{color =} \StringTok{"\#2E86AB"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{color =} \StringTok{"\#E74C3C"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Linear Relationship Between Depression (CESD{-}R) and Suicidal Risk (SABCS)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Depression (CESD{-}R Total Score)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Suicidal Risk (SABCS Total Score)"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Activity-3_trial1_files/figure-latex/unnamed-chunk-10-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#  Extract regression coefficients for equation}
\FunctionTok{coef}\NormalTok{(lm\_line)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     (Intercept) CESDR_TOTAL_SUM 
##      0.01087968      0.20899857
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# (optional) store intercept and slope for display}
\NormalTok{intercept }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(lm\_line)[}\DecValTok{1}\NormalTok{]}
\NormalTok{slope }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(lm\_line)[}\DecValTok{2}\NormalTok{]}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Estimated regression equation:}\SpecialCharTok{\textbackslash{}n}\StringTok{SABCS ="}\NormalTok{, }\FunctionTok{round}\NormalTok{(intercept, }\DecValTok{2}\NormalTok{),}
    \StringTok{"+"}\NormalTok{, }\FunctionTok{round}\NormalTok{(slope, }\DecValTok{2}\NormalTok{), }\StringTok{"× CESD{-}R}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Estimated regression equation:
## SABCS = 0.01 + 0.21 × CESD-R
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate R{-}squared manually (for reporting)}
\NormalTok{r\_squared }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(lm\_line)}\SpecialCharTok{$}\NormalTok{r.squared}
\FunctionTok{cat}\NormalTok{(}\StringTok{"R{-}squared:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(r\_squared, }\DecValTok{3}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## R-squared: 0.347
\end{verbatim}

Because the scatterplot showed a clear positive linear trend between
depression (CESD-R) and suicidal risk (SABCS), fitting a line of best
fit was appropriate. The estimated regression equation was:

SABCS=0.01+0.21×CESD-R

This means that for every 1-point increase in the CESD-R depression
score, the predicted suicidal risk score increases by about 0.21 points
on average. The positive slope indicates that higher depression scores
are associated with higher suicidal risk.

\section{Linear Regression Analysis (α =
0.05)}\label{linear-regression-analysis-ux3b1-0.05}

The regression model revealed a statistically significant positive
relationship between depression and suicidal risk (F(1, 544) = 289.4, p
\textless{} 0.001). The slope for depression (β = 0.21) was significant
(p \textless{} 0.001), indicating that depression scores were a strong
predictor of suicidal risk scores. The model explained approximately
34.7\% of the variance in suicidal risk (R² = 0.35), suggesting a
substantial association.

Plain-language interpretation: The analysis shows that individuals with
higher depression levels tend to report higher suicidal-risk scores. The
relationship is statistically significant and moderately strong, meaning
that depression accounts for a large portion of the differences in
suicidal risk among participants.

\subsection{6. This problem will focus on quantifying the association
between suicidal risk (Suicidal Affect-Behavior-Cognition Scale
{[}SABCS{]}) and age, including the form, direction, and strength of
their
relationship}\label{this-problem-will-focus-on-quantifying-the-association-between-suicidal-risk-suicidal-affect-behavior-cognition-scale-sabcs-and-age-including-the-form-direction-and-strength-of-their-relationship}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Scatterplot of Age vs. Suicidal Risk}
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ AGE, }\AttributeTok{y =}\NormalTok{ SABCS\_TOTAL\_SUM)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{color =} \StringTok{"\#2E86AB"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{color =} \StringTok{"\#E74C3C"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Relationship Between Age and Suicidal Risk (SABCS)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Age (years)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Suicidal Risk (SABCS Total Score)"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Activity-3_trial1_files/figure-latex/unnamed-chunk-11-1.pdf}}

The scatterplot shows a generally flat pattern with no clear upward or
downward trend. This suggests that suicidal risk scores do not change
substantially with age in this sample. The fitted regression line
indicates that the relationship between age and suicidal risk is weak.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Pearson correlation between suicidal risk and age}
\NormalTok{cor\_age }\OtherTok{\textless{}{-}} \FunctionTok{cor.test}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{SABCS\_TOTAL\_SUM, data}\SpecialCharTok{$}\NormalTok{AGE, }\AttributeTok{method =} \StringTok{"pearson"}\NormalTok{)}
\NormalTok{cor\_age}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  data$SABCS_TOTAL_SUM and data$AGE
## t = -1.7567, df = 544, p-value = 0.07953
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.158022264  0.008862322
## sample estimates:
##         cor 
## -0.07510585
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check linearity visually (scatterplot above)}
\CommentTok{\# Check normality of both variables}
\FunctionTok{shapiro.test}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{AGE)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  data$AGE
## W = 0.74319, p-value < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{SABCS\_TOTAL\_SUM)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  data$SABCS_TOTAL_SUM
## W = 0.7098, p-value < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm\_age }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(SABCS\_TOTAL\_SUM }\SpecialCharTok{\textasciitilde{}}\NormalTok{ AGE, }\AttributeTok{data =}\NormalTok{ data)}
\FunctionTok{summary}\NormalTok{(lm\_age)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = SABCS_TOTAL_SUM ~ AGE, data = data)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.634 -3.353 -1.792  1.366 28.478 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  4.70011    0.82036   5.729 1.67e-08 ***
## AGE         -0.05611    0.03194  -1.757   0.0795 .  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.85 on 544 degrees of freedom
## Multiple R-squared:  0.005641,   Adjusted R-squared:  0.003813 
## F-statistic: 3.086 on 1 and 544 DF,  p-value: 0.07953
\end{verbatim}

\section{Visualization}\label{visualization-1}

The scatterplot of age and suicidal risk shows a flat distribution,
indicating that suicidal risk scores remain relatively constant across
ages. The fitted regression line is almost horizontal, suggesting that
age has little or no relationship with suicidal risk.

\section{Estimation}\label{estimation-1}

The Pearson correlation between age and suicidal risk was r = --0.075,
95\% CI {[}--0.158, 0.009{]}, p = 0.080. This indicates a very weak,
negative association---older participants tended to report slightly
lower suicidal risk scores, but the difference is extremely small.

\section{Test of Assumptions}\label{test-of-assumptions-1}

The scatterplot indicates no major outliers and an approximately linear
pattern, meeting the linearity assumption. However, the Shapiro--Wilk
tests for both variables were significant (W = 0.74 for age and W = 0.71
for suicidal risk, both p \textless{} 0.001), meaning both distributions
deviate from normality. Because the sample size is large (n = 546),
Pearson's correlation remains robust to non-normality, so the analysis
is still valid.

\section{Test of Correlation (alpha =
0.05)}\label{test-of-correlation-alpha-0.05}

The correlation between age and suicidal risk was not statistically
significant (r = --0.075, p = 0.08). This means there is no reliable
evidence of an association between age and suicidal risk in this sample.
In plain language, participants' suicidal thoughts, feelings, and
behaviors were similar across all age groups, with no clear trend as age
increased.

\section{Linear Regression and Fitted
Line}\label{linear-regression-and-fitted-line}

Because the scatterplot showed an approximately linear (though weak)
pattern, fitting a line of best fit was appropriate. The regression
equation was: SABCS=4.87−0.03×Age

The slope was not statistically significant (p = 0.08), and the model
explained less than 1\% of the variance in suicidal risk (R² \textless{}
0.01). This confirms that age does not meaningfully predict suicidal
risk.

\section{Plain-Language Summary}\label{plain-language-summary}

Both the correlation and regression analyses showed that age was not
significantly related to suicidal risk. Although the relationship was
slightly negative, the effect was very small and not statistically
meaningful. Overall, suicidal risk remains relatively constant across
age, suggesting that age alone is not a strong factor influencing
suicidal thoughts or behaviors.

\end{document}
